image: migamake/haskell-build:8.6.2

stages:
  - build
  - test

cache:
  paths:
    - $HOME/.cabal/packages

install_dependencies:
  stage: build
  script:
    - cabal --version
    - ghc --version
    - pwd
    - ls
    - cabal update
    - cabal install --verbose --only-dependencies

install_exe:
  stage: build
  script:
    - cabal --version
    - ghc --version
    - pwd
    - ls
    - cabal update
    - cabal install --verbose --only-dependencies
    - "sed --in-place 's/-- STATIC: //' homplexity.cabal"
    - cabal install --bindir=/usr/local/bin
  artifacts:
    paths:
      - /usr/local/bin/homplexity

cabal_tests:
  stage: build
  script:
    - cabal test
    - cabal bench || exit 0


executable_test:
  stage: test
  script:
    - cabal --version
    - ghc --version
    - pwd
    - ls
    - cabal exec homplexity-cli Language/
    - homplexity-cli Language/
