image: migamake/haskell-build:8.6.2

stages:
  - build
  - test

cache:
  paths:
    - $HOME/.cabal

install_dependencies:
  stage: build
  script:
    - cabal update
    - cabal sandbox init
    - cabal install --verbose --only-dependencies
    - cabal install
#  artifacts:
#    paths:
#      - .cabal-sandbox/bin

test_with_lab:
  stage: test
  script:
    - homplexity-cli Language/
    - cabal test
    - cabal bench || exit 0
