image: migamake/haskell-build:8.6.2

stages:
  - build
  - test

cache:
  paths:
    - $HOME/.cabal

install_dependencies:
  stage: build
  script:
    - cabal update
    - cabal sandbox init
    - cabal install --only-dependencies
  artifacts:
    paths:
      - .cabal-sandbox

test_with_lab:
  stage: test
  script:
    - cabal test
    - cabal bench || exit 0
