image: migamake/haskell-build:8.6.2

stages:
  - build

cache:
  paths:
    - $HOME/.cabal

install_dependencies:
  stage: build
  script:
    - cabal --version
    - ghc --version
    - pwd
    - ls
    - cabal update
    - cabal install --verbose --only-dependencies

install_exe:
  stage: build
  script:
    - cabal --version
    - ghc --version
    - pwd
    - ls
    - cabal update
    - cabal install --verbose --only-dependencies
    - "sed --in-place 's/-- STATIC: //' homplexity.cabal"
    - cabal install --bindir=/usr/local/bin
  artifacts:
    paths:
      - /usr/local/bin/homplexity
  dependencies:
    - install_dependencies


cabal_tests:
  stage: build
  script:
    - cabal test
    - cabal bench || exit 0
  dependencies:
    - install_dependencies
    - install_exe

executable_test:
  stage: build
  script:
    - which homplexity-cli
    - cabal --version
    - ghc --version
    - pwd
    - ls
    - cabal exec homplexity-cli Language/
    - homplexity-cli Language/
